### ISSUE TITLE
LGPL

### ISSUE THREAD

**Issue by amirouche** [ibawt/chezuv#5]
Hello!

I am working on getting together a set of good and useful libraries for Chez Scheme @ https://github.com/arew-scheme/arew-scheme.

chezuv is a good candidate but it use an incompatible license. Can you change the license to LGPL?

**Comment by amirouche** [comment]
By the way so far, I mostly forked the libraries (SRFI libraries) but I am willing to make the effort to work together on this.

What do you think?

**Comment by amirouche** [comment]
Please :heart:

**Comment by ibawt** [comment]
No thanks.
